### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by cronner** [maluklo/Skin-video-js-6.2.6#1]
Works great

I'm trying to add dynamic switcher but the gear icon is there and it does not look good, can you help? :)
Also trying with speed, ie8 fix and flash fallback but can't seem to make it work
![1](https://user-images.githubusercontent.com/5718401/29667118-77d3b962-88db-11e7-8124-1e1080735e4f.jpg)

Tried:
videojs('play2').videoJsResolutionSwitcher({

          ui: true,
          default: 'low', // Default resolution [{Number}, 'low', 'high'],
          dynamicLabel: true, // Display dynamic labels or gear symbol

})

**Comment by maluklo** [comment]
Olá segue;
https://github.com/maluklo/video-js-6.2.6/blob/master/resolution-switcher.html
